[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Introduction to Python"
authors = [{name = "Python module", email = "python-module@testing"}]
dynamic = ["version", "description"]
